# Generated by Django 4.1.6 on 2023-02-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_remove_medicine_price_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pharmacymedicine',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
